apiVersion: v1
kind: Namespace
metadata:
  name: serval
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: serval
  namespace: serval
  labels:
    app: serval
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: serval-role
  labels:
    app: serval
rules:
- apiGroups: ['*']
  resources: ['namespaces']
  verbs: ["get", "list"]
- apiGroups: ['*']
  resources: ['runs', 'runs/status']
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ['*']
  resources: ['pipelineruns']
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: serval-role-binding
  labels:
    app: serval
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: serval-role
subjects:
- kind: ServiceAccount
  name: serval
  namespace: serval
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: authorization-configmap-access-for-serval
  namespace: serval
  labels:
    app: serval
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["serval-authorization"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: serval-role-binding-for-authorization-configmap
  namespace: serval
  labels:
    app: serval
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: authorization-configmap-access-for-serval
subjects:
- kind: ServiceAccount
  name: serval
  namespace: serval