apiVersion: v1
kind: ConfigMap
metadata:
  name: feature-flags
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
data:
  disable-affinity-assistant: "false"
  disable-home-env-overwrite: "true"
  disable-working-directory-overwrite: "true"
  disable-creds-init: "false"
  running-in-environment-with-injected-sidecars: "true"
  require-git-ssh-secret-known-hosts: "false"
  enable-tekton-oci-bundles: "false"
  enable-custom-tasks: "true" # altered - serval is about custom tasks :-)
  enable-api-fields: "alpha" # altered - for gracefull stop/cancel of pipelines