apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-access-for-serval
  namespace: pipelines
  labels:
    app: serval
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["serval"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: serval-role-binding
  namespace: pipelines
  labels:
    app: serval
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-access-for-serval
subjects:
- kind: ServiceAccount
  name: serval
  namespace: serval