apiVersion: v1
kind: Namespace
metadata:
  name: serval
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: serval
  namespace: serval
  labels:
    app: serval
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: serval-role
  labels:
    app: serval
rules:
- apiGroups: ['*']
  resources: ['runs', 'runs/status']
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ['*']
  resources: ['pipelineruns']
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: serval-role-binding
  labels:
    app: serval
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: serval-role
subjects:
- kind: ServiceAccount
  name: serval
  namespace: serval